#!/bin/sh
### BEGIN INIT INFO
# Provides:          roc_uart
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Remap pins for UART2&3 (/dev/ttyAPP2&3)
### END INIT INFO

# Set environment variable values
export UART2_RXD=FPGA_22
export UART3_RXD=FPGA_24
export FPGA_26=UART3_TXD
export FPGA_28=UART2_TXD
export MODBUS_TXD=GPIO
export MODBUS_TXEN=GPIO
export RS_485_TXD=GPIO
export RS_485_TXEN=GPIO

# Make new settings active
tshwctl --set

# Set TX pins as outputs
echo "196" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio196/direction
echo "198" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio198/direction

