#!/bin/sh
### BEGIN INIT INFO
# Provides:          roc_led
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Configure GPIO pins to drive red/green LED
### END INIT INFO

# Set environment variables
export LED_RED=/sys/class/gpio/gpio195/value
export LED_GRN=/sys/class/gpio/gpio197/value

# Configure GPIO and set outputs low
if test ! -e /sys/class/gpio/gpio195 ; then
	echo "195" > /sys/class/gpio/export
fi
echo "out" > /sys/class/gpio/gpio195/direction
echo "0"   > $LED_RED
if test ! -e /sys/class/gpio/gpio197 ; then
	echo "197" > /sys/class/gpio/export
fi
echo "out" > /sys/class/gpio/gpio197/direction
echo "0"   > $LED_GRN
