#!/bin/sh
### BEGIN INIT INFO
# Provides:          roc
# Required-Start:    $local_fs $network $syslog $roc_uart $roc_gpio
# Required-Stop:     $local_fs $network $syslog $roc_uart $roc_gpio
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Starts ROC data collection software
### END INIT INFO

sleep 5		# wait for digital IO config to complete
/opt/roc/roc &> /root/roc_log.txt &
/opt/roc/zephyr &> /root/zephyr_log.txt &

