#!/bin/sh
### BEGIN INIT INFO
# Provides:          roc
# Required-Start:    $local_fs $network $syslog $roc_uart $roc_led
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Starts ROC data collection software
### END INIT INFO

/opt/roc/roc -v &> /root/roc_log.txt &
exec /opt/roc/zephyr -v &> /root/zephyr_log.txt &
#ifdown wlan0
